name       : haskell-splitmix
version    : 0.1.0.4
release    : 2
source     :
    - https://hackage.haskell.org/package/splitmix-0.1.0.4/splitmix-0.1.0.4.tar.gz : 6d065402394e7a9117093dbb4530a21342c9b1e2ec509516c8a8d0ffed98ecaa
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast Splittable PRNG
description: |
    Pure Haskell implementation of SplitMix
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
