name       : haskell-splitmix
version    : 0.0.5
release    : 1
source     :
    - https://hackage.haskell.org/package/splitmix-0.0.5/splitmix-0.0.5.tar.gz : 19f2987ba707c935656371776639588c3252cbb44b66cae16107b13e73b4cd52
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast Splittable PRNG
description: |
    Pure Haskell implementation of SplitMix
builddeps  :
    - haskell-cabal-install
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
